# Generated by Django 4.2.5 on 2023-11-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_favorite_tutors_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student',
        ),
    ]
