# Generated by Django 4.2.6 on 2023-11-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_email_remove_student_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.AutoField(db_column='studentID', editable=False, primary_key=True, serialize=False),
        ),
    ]
