# Generated by Django 4.2.5 on 2023-11-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_student_id_student_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite_Tutors_Manager',
        ),
    ]
