# Generated by Django 4.2.6 on 2023-11-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.AutoField(db_column='studentIDs', editable=False, primary_key=True, serialize=False),
        ),
    ]
