# Generated by Django 4.2.6 on 2023-11-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_delete_favorite_tutors_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
