# Generated by Django 4.2.6 on 2023-11-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_studentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite_Tutors',
        ),
    ]
