# Generated by Django 4.2.6 on 2023-11-02 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '__first__'),
        ('student', '0007_delete_favorite_tutors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_Tutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('tutorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor')),
            ],
            options={
                'db_table': 'favorite_tutors',
                'managed': True,
            },
        ),
    ]
