# Generated by Django 4.2.6 on 2023-11-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_favorite_tutors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentid',
            new_name='student',
        ),
    ]
