# Generated by Django 4.2.6 on 2023-11-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_rename_studentid_student_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite_tutors',
            old_name='studentid',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='favorite_tutors',
            old_name='tutorid',
            new_name='tutor',
        ),
    ]
