# Generated by Django 4.2.6 on 2023-11-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_rename_studentid_favorite_tutors_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite_Tutors',
        ),
    ]
