# Generated by Django 4.2.6 on 2023-11-07 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_hours', models.IntegerField(blank=True, default=0)),
                ('subject_list', models.CharField(blank=True, max_length=1000, null=True)),
                ('biography', models.CharField(blank=True, max_length=1000, null=True)),
                ('hours', models.CharField(blank=True, max_length=1000, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=1000, null=True)),
                ('background_checked', models.BooleanField(blank=True, default=False)),
                ('available', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'tutor',
                'managed': True,
            },
        ),
    ]
