# Generated by Django 4.2.6 on 2023-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutorid', models.AutoField(db_column='tutorID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('subject_list', models.CharField(blank=True, max_length=100, null=True)),
                ('about_me', models.CharField(blank=True, max_length=100, null=True)),
                ('hours', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('total_hours', models.IntegerField(blank=True, null=True)),
                ('background_checked', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
    ]
