# Generated by Django 4.2.6 on 2023-11-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor_about_me_tutor_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='about_me',
            new_name='biography',
        ),
    ]
