# Generated by Django 4.2.6 on 2023-11-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutorsubjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='subject_list',
        ),
    ]
