# Generated by Django 4.2.5 on 2023-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_alter_tutor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutorid',
            field=models.AutoField(db_column='tutorID', editable=False, primary_key=True, serialize=False),
        ),
    ]
