# Generated by Django 4.2.5 on 2023-11-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointments_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='tutor_id',
            new_name='tutor',
        ),
    ]
