# Generated by Django 4.2.5 on 2023-11-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_student_id_appointments_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='location',
            field=models.CharField(default='online', max_length=100),
        ),
    ]
