# Generated by Django 4.2.6 on 2023-11-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointments_location'),
    ]

    operations = [
    ]
