# Generated by Django 4.2.6 on 2023-11-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_date_field_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
