# Generated by Django 4.2.5 on 2023-11-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duo_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
